#spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/finance_index?characterEncoding=UTF-8&&serverTimezone=GMT
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      show-sql: true
#      properties:
#        hibernate:
#          format_sql: true
